# Generated by Django 3.1.4 on 2020-12-20 20:03
# Generated by Django 3.1.4 on 2020-12-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201217_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_image_url', models.URLField(max_length=2000)),
                ('product_image_url', models.URLField(max_length=2000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'detailed_images',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('detailed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.detailedimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_descriptions',
            },
        ),
    ]
