# Generated by Django 3.1.4 on 2020-12-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201217_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='often_buying',
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default='2020-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommender',
            field=models.CharField(blank=True, default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_and_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.termsandcondition'),
        ),
        migrations.DeleteModel(
            name='OftenBuying',
        ),
    ]
