# Generated by Django 3.1.4 on 2020-12-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201217_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oftenbuying',
            name='quantity',
        ),
    ]
