# Generated by Django 3.1.4 on 2020-12-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0004_auto_20201217_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommender',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_and_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.termsandcondition'),
        ),
        migrations.CreateModel(
            name='OftenBuying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'often_buyings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='often_buying',
            field=models.ManyToManyField(related_name='often_buying_set', through='user.OftenBuying', to='product.Product'),
        ),
    ]
