# Generated by Django 3.1.4 on 2020-12-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201219_1312'),
        ('user', '0004_remove_oftenbuying_quantity'),
    ]

    operations = [
    ]
