# Generated by Django 3.1.4 on 2020-12-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='has_comment',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.questioncomment'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='title',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
