# Generated by Django 3.1.4 on 2020-12-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='order_cart_set', through='order.Cart', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cart_order_set', to='order.order'),
        ),
        migrations.DeleteModel(
            name='OftenBuying',
        ),
    ]
