# Generated by Django 3.1.4 on 2020-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201217_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
